spring:
  application:
    name: auth-server
server:
  port: 8001

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://admin:admin@localhost:8000/eureka/
